site_name: ROSbloX
site_url: https://rosblox.github.io/
nav:
      - 'The ROSbloX documentation': index.md
      - 'Connecting to ROSbloX': 'connection.md'
      - 'The ROSbloX interfaces': 'interface.md'
      - 'Further Reading': 'background.md'

repo_url: https://github.com/rosblox/rosblox.github.io
edit_uri: edit/main/docs

theme:
  name: readthedocs
  logo: assets/logo.png
  include_homepage_in_sidebar: true
  collapse_navigation: true
  analytics:
    gtag: G-VDKN1X1DXK
